.

diff --git a/templates/restic_script_multi_Linux.j2 b/templates/restic_script_multi_Linux.j2
--- a/templates/restic_script_multi_Linux.j2
+++ b/templates/restic_script_multi_Linux.j2
@@ -126,6 +126,13 @@ fi
       {{ stdin_filename(stdin_cmd.stdin_filename) }} \
       {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
       $@ \
+      {{ backup_output_log }}
+      if [[ $? -eq 0 ]]
+      then
+          echo "$(date -u '+%Y-%m-%d %H:%M:%S') {{ stdin_cmd.cmd }} OK" {{ backup_result_log }}
+      else
+          echo "$(date -u '+%Y-%m-%d %H:%M:%S') {{ stdin_cmd.cmd }} ERROR" {{ backup_result_log }}
+      fi
   {% endfor %}
 {% else %}
   {% for src in item.srcs %}
@@ -133,28 +140,30 @@ fi
       {{ tags(item.tags) }} \
       {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
       $@ \
+      {{ backup_output_log }}
+      if [[ $? -eq 0 ]]
+      then
+          echo "$(date -u '+%Y-%m-%d %H:%M:%S') {{ src }} OK" {{ backup_result_log }}
+      else
+          echo "$(date -u '+%Y-%m-%d %H:%M:%S') {{ src }} ERROR" {{ backup_result_log }}
+      fi
   {% endfor %}
-{% endif %} {{ backup_output_log }}
-if [[ $? -eq 0 ]]
-then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" {{ backup_result_log }}
-else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" {{ backup_result_log }}
-fi
+{% endif %}
 
 
-{% if item.forget is not defined or item.forget == true %}
 {#
   Define stdin forget commands
 #}
 
 {% if item.stdin is defined and item.stdin == true %}
   {% for stdin_cmd in item.stdin_cmds %}
-    {{ restic_install_path }}/restic forget --path {{ stdin_cmd.stdin_filename }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} {{ forget_output_log }}
+    {{ restic_install_path }}/restic forget --path {{ stdin_cmd.stdin_filename }} {{ retention_pattern(item) }} \
+    {{ forget_output_log }}
   {% endfor %}
 {% else %}
   {% for src in item.srcs %}
-    {{ restic_install_path }}/restic forget --path {{ src }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} {{ forget_output_log }}
+    {{ restic_install_path }}/restic forget --path {{ src }} {{ retention_pattern(item) }}  \
+    {{ forget_output_log }}
   {% endfor %}
 {% endif %}
 if [[ $? -eq 0 ]]
@@ -170,4 +179,19 @@ else
       {{ ' ' }}Please repair the restic-{{ item.name | replace(' ', '') }} job."
     {% endif %}
 fi
+{% if item.prune is defined and item.prune == true %}
+  {{ restic_install_path }}/restic prune
+  if [[ $? -eq 0 ]]
+  then
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') PRUNE OK" {{ forget_result_log }}
+  else
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') PRUNE ERROR" {{ forget_result_log }}
+      {% if item.mail_on_error is defined and item.mail_on_error == true %}
+      mail -s "restic backup failed on {{ ansible_hostname }}" {{ item.mail_address }}  <<< "Something went wrong while running restic backup script running at {{ ansible_hostname }} at $(date -u '+%Y-%m-%d %H:%M:%S').
+        {%- if item.src is defined -%}
+          {{ ' ' }}We tried to backup '{{ item.src }}'.
+        {%- endif -%}
+        {{ ' ' }}Please repair the restic-{{ item.name | replace(' ', '') }} job."
+      {% endif %}
+  fi
 {% endif %}
